sudo: required
language: java
jdk:
  -openjdk8


services: 
  - docker
  
befor_install: 
  - docker build -t my-order-ms .
  
script: 
  - ./mvnw clean install -DskipTests
  - docker run my-order-ms mvn clean install -DskipTests
